import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['font.sans-serif'] = ['SimHei']
plt.rcParams['axes.unicode_minus'] = False
df_gen = pd.read_csv('Plant_1_Generation_Data.csv')
df_weather = pd.read_csv('Plant_1_Weather_Sensor_Data.csv')
print("✅ 数据读取成功！")
print("发电数据前5行：")
print(df_gen.head())
print("\n气象数据前5行：")
print(df_weather.head())
df_gen['DATE_TIME'] = pd.to_datetime(df_gen['DATE_TIME'])
df_weather['DATE_TIME'] = pd.to_datetime(df_weather['DATE_TIME'])
df_merged = pd.merge(df_gen, df_weather, on=['DATE_TIME'], how='inner')
print("合并后的数据形状 (行数, 列数):", df_merged.shape)
print("合并后数据的缺失值统计：")
print(df_merged.isnull().sum())
df_merged = df_merged.dropna()
df_daytime = df_merged[df_merged['IRRADIATION'] > 0].copy()
print("\n白天数据形状:", df_daytime.shape)
first_date = df_daytime['DATE_TIME'].dt.date.unique()[0]
sample_day = df_daytime[df_daytime['DATE_TIME'].dt.date == first_date]
sample_day = sample_day.sort_values('DATE_TIME')
plt.figure(figsize=(12, 4))
plt.plot(sample_day['DATE_TIME'], sample_day['AC_POWER'], label='AC Power', color='orange')
plt.title(f'One Day AC Power Generation Curve ({first_date})')
plt.xlabel('Time')
plt.ylabel('AC Power (kW)')
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.figure(figsize=(8, 6))
plt.scatter(df_daytime['IRRADIATION'], df_daytime['AC_POWER'], alpha=0.3, color='orange')
plt.title('Relationship between Irradiation and AC Power')
plt.xlabel('Irradiation (W/m2)')
plt.ylabel('AC Power (kW)')
plt.tight_layout()
plt.show()
plt.figure(figsize=(8, 4))
plt.hist(df_daytime['AMBIENT_TEMPERATURE'], bins=30, color='skyblue', edgecolor='black')
plt.title('Distribution of Ambient Temperature during Daytime')
plt.xlabel('Ambient Temperature (°C)')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()